import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
const URL='http://127.0.0.1:4477', OUT=process.argv[2]||'shots/rr-look';
await mkdir(OUT,{recursive:true});
const b=await chromium.launch({args:['--use-gl=angle','--ignore-gpu-blocklist','--enable-unsafe-swiftshader','--disable-gpu-vsync','--disable-frame-rate-limit']});
const ctx=await b.newContext({viewport:{width:1440,height:810},deviceScaleFactor:1});
const page=await ctx.newPage();
const errs=[]; page.on('console',m=>{if(m.type()==='error')errs.push(m.text())}); page.on('pageerror',e=>errs.push('PE '+e.message));
await page.addInitScript(()=>{try{localStorage.clear()}catch{}});
await page.goto(URL,{waitUntil:'networkidle'});
await page.waitForFunction(()=>!!window.__ascent,null,{timeout:30000});
await page.waitForTimeout(3200);
await page.screenshot({path:OUT+'/00-spawn.png'});
await page.mouse.move(720,405); await page.mouse.click(720,405);
await page.waitForTimeout(400);
await page.keyboard.down('KeyW');
await page.waitForTimeout(4200);
await page.screenshot({path:OUT+'/01-approach.png'});
await page.waitForTimeout(2200);
await page.screenshot({path:OUT+'/02-close.png'});
await page.keyboard.up('KeyW');
await page.waitForTimeout(1200);
await page.screenshot({path:OUT+'/03-contact.png'});
console.log(JSON.stringify(await page.evaluate(()=>({p:window.__ascent.player.pos.toArray().map(v=>+v.toFixed(1)),panel:window.__ascent.panel.open}))));
console.log('ERRORS',errs.slice(0,5));
await b.close();
