import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
const URL = 'http://127.0.0.1:4917';
const OUT = '/tmp/cohplay/shots';
await mkdir(OUT, { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--use-gl=angle','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 1600, height: 900 } });
const page = await ctx.newPage();
const errs = [];
page.on('pageerror', e => errs.push('pageerror: ' + e.message));
page.on('console', m => { if (m.type() === 'error') errs.push('console: ' + m.text()); });
await page.goto(URL, { waitUntil: 'networkidle' });
await page.evaluate(() => { try { localStorage.clear(); sessionStorage.clear(); } catch {} });
await page.reload({ waitUntil: 'networkidle' });
await page.waitForFunction(() => !!window.__ascent, null, { timeout: 40000 });
await page.waitForTimeout(5000);
await page.screenshot({ path: OUT + '/00-arrival.png' });
const dom = await page.evaluate(() => {
  const ui = document.getElementById('ui');
  const ids = [...document.querySelectorAll('[id]')].map(e => e.id);
  return { text: ui ? ui.innerText : '(no #ui)', ids: ids.slice(0,120), body: document.body.innerText.slice(0,3000) };
});
console.log('--- UI TEXT ---'); console.log(dom.text);
console.log('--- IDS ---'); console.log(dom.ids.join(' '));
const st = await page.evaluate(() => { const a = window.__ascent; return { content: a.content(), objective: a.objective(), session: a.session.state(), locale: a.locale() }; });
console.log('--- CONTENT ---'); console.log(JSON.stringify(st.content, null, 1).slice(0, 3000));
console.log('--- OBJECTIVE ---'); console.log(JSON.stringify(st.objective));
console.log('--- SESSION ---'); console.log(JSON.stringify(st.session, null, 1).slice(0,2500));
console.log('--- ERRORS ---'); console.log(errs.join('\n') || '(none)');
await browser.close();
