#!/usr/bin/env node
/**
 * Rebuild `content/standards/algebra1-l2-standards-map.md` from the graph.
 *
 * WHY THIS EXISTS. The Level 1 map is generated by `tools/validate-items.mjs`,
 * so it cannot disagree with the graph it documents. The Level 2 map was
 * written by hand, and within one audit it was already stale: four alignment
 * rows had changed depth or wording in the graph and the document still
 * carried the old ones. A standards document that drifts from the machine-
 * readable source is worse than no document, because it is the copy a
 * department head reads.
 *
 * So the document is derived, and this tool derives it.
 *
 *   node tools/build-l2-map.mjs                        # rewrite Level 2
 *   node tools/build-l2-map.mjs --unit algebra1-l3      # …or any other unit
 *   node tools/build-l2-map.mjs --check                 # non-zero if stale
 *
 * `--unit` was added when Level 3 landed. The document a department head reads
 * must be derived from the graph rather than typed beside it, and that is as
 * true of the third unit as of the second, so the tool takes the unit id
 * instead of carrying one in a constant. With no flag it rewrites Level 2,
 * byte for byte as before.
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { alignmentOf, practicesOf, alignmentNote, FRAMEWORKS } from '../src/content/standards.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const argOf = (k) => { const i = process.argv.indexOf(k); return i >= 0 ? process.argv[i + 1] : null; };
const UNIT = argOf('--unit') || 'algebra1-l2';
const GRAPH = path.join(ROOT, `content/graph/${UNIT}.json`);
const OUT = path.join(ROOT, `content/standards/${UNIT}-standards-map.md`);
const CHECK = process.argv.includes('--check');

const graph = JSON.parse(await readFile(GRAPH, 'utf8'));

/* IS A CLASS ACTUALLY SENT HERE? Read out of the manifest, never written here.
   A working paper for a unit nobody is routed to reads exactly like a working
   paper for a unit every class receives, and a department head opening one of
   these on its own has no way to tell them apart. That is the same conflation
   content/STANDARDS.md section 1 exists to undo, one document further down. */
const manifest = JSON.parse(await readFile(path.join(ROOT, 'content/courses.json'), 'utf8'));
const COURSE = manifest.courses.find((c) => c.id === (manifest.route?.course || manifest.default?.course));
const ROUTE = (manifest.route?.units?.length
  ? manifest.route.units
  : (COURSE?.units || []).filter((u) => u.status === 'shipped').map((u) => u.id));
const ON_ROUTE = ROUTE.includes(UNIT);

const out = [];
const p = (s = '') => out.push(s);

p(`# Standards alignment — ${graph.title}`);
p();
p(ON_ROUTE
  ? `> **A class receives this unit.** \`${UNIT}\` is on the shipped route in `
    + '`content/courses.json`, so a learner with no query string and a cleared save reaches it. '
    + 'Everything below is coverage a class actually meets.'
  : `> **A CLASS DOES NOT RECEIVE THIS UNIT.** \`${UNIT}\` is \`preview\` in `
    + '`content/courses.json`: it is written, validated and shipped in the bundle, and the route a '
    + 'learner walks with no query string does not reach it. Nothing below is coverage a class meets '
    + `today. Reaching it needs \`?unit=${UNIT}\` typed into the address bar. See `
    + '[`../STANDARDS.md`](../STANDARDS.md) section 1 for what a class does receive, and section 5.5 '
    + 'for what is holding this unit back.');
p();
p(`Generated from \`content/graph/${UNIT}.json\`, which is the source of truth, by`);
p(`\`node tools/build-l2-map.mjs${UNIT === 'algebra1-l2' ? '' : ` --unit ${UNIT}`}\`. Do not edit this file: edit the graph and rebuild.`);
p('Every claim below is made by a node and is read through `src/content/standards.js`.');
p();
p('**How to read a depth.** `core` means the mastery gate for that node really tests the');
p('expectation: three unassisted items at band 4 or above, at least one of them outside');
p('notation, in a form or a situation the learner has not practised. `supporting` and');
p('`introduced` mean part of the expectation is met and the row says which part is not.');
p();

const v = graph.verification;
if (v) {
  p('## Verification');
  p();
  p(`Citations last checked **${v.checkedOn}**, against:`);
  p();
  for (const s of v.sources) p(`- ${s}`);
  p();
  p(v.note);
  p();
  for (const c of v.caveats || []) p(`- ${c}`);
  p();
}

if (v && (v.declaredGaps || []).length) {
  p('## Declared gaps — codes this unit does NOT claim');
  p();
  p('A unit is judged as much by what it refuses to claim as by what it cites. Each row');
  p('below is an expectation a reader might reasonably expect to find above, together with');
  p('the reason it is absent. None of these codes appears anywhere in this unit\'s alignment.');
  p();
  p('| Code | 19 TAC | Claim | Why not |');
  p('|---|---|---|---|');
  for (const g of v.declaredGaps) {
    p(`| \`${g.code}\` | ${g.citation ? `\`${g.citation}\`` : '—'} | ${g.claim} | ${g.why} |`);
  }
  p();
}

p('## Coverage');
p();
p('| Framework | Distinct codes | Claimed `core` |');
p('|---|---|---|');
for (const fw of Object.keys(FRAMEWORKS)) {
  const rows = graph.nodes.flatMap((n) => alignmentOf(n)).filter((a) => a.framework === fw);
  const codes = new Set(rows.map((a) => a.code));
  const core = new Set(rows.filter((a) => a.depth === 'core').map((a) => a.code));
  if (!codes.size) continue;
  p(`| ${FRAMEWORKS[fw].label} | ${codes.size} | ${core.size} |`);
}
p();
p('Process standards are cited under `practices` and are **not** counted as content');
p('coverage. A process standard is how a learner works, not what the unit teaches.');
p();

for (const n of graph.nodes) {
  p(`## \`${n.id}\``);
  p();
  p(`> ${n.bigIdea}`);
  p();
  p(`**Prerequisites.** ${n.prereqs.length ? n.prereqs.map((x) => `\`${x}\``).join(', ') : '— (this unit opens here)'}`);
  p();
  p('| Framework | Code | 19 TAC | Depth | Expectation |');
  p('|---|---|---|---|---|');
  const al = alignmentOf(n);
  for (const a of al) {
    p(`| ${a.framework} | \`${a.code}\` | ${a.citation ? `\`${a.citation}\`` : '—'} | ${a.depth} | ${a.text} |`);
  }
  p();
  const caveats = al.filter((a) => a.caveat);
  if (caveats.length) {
    for (const a of caveats) p(`- **${a.code} — what is NOT claimed.** ${a.caveat}`);
    p();
  }
  p('**What the gate proves.**');
  p();
  for (const fw of Object.keys(FRAMEWORKS)) {
    const note = alignmentNote(n, fw);
    if (note) p(`- *${fw}* — ${note}`);
  }
  p();
  const pr = practicesOf(n);
  const parts = Object.entries(pr).filter(([, l]) => l.length).map(([fw, l]) => `${fw} ${l.join(', ')}`);
  p(`**Process standards.** ${parts.join(' · ')}`);
  p();
  p(`**Misconceptions this node declares.** ${(n.misconceptions || []).map((m) => `\`${m.id}\``).join(', ')}`);
  p();
}

const body = out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
if (CHECK) {
  const now = await readFile(OUT, 'utf8').catch(() => '');
  if (now !== body) {
    console.error(`content/standards/${UNIT}-standards-map.md is out of date — run node tools/build-l2-map.mjs --unit ${UNIT}`);
    process.exit(1);
  }
  console.log(`${UNIT} standards map is in step with the graph.`);
} else {
  await writeFile(OUT, body);
  console.log(`wrote ${path.relative(ROOT, OUT)} — ${graph.nodes.length} nodes`);
}
