#!/usr/bin/env node
/**
 * Rebuild `content/standards/algebra1-l2-standards-map.md` from the graph.
 *
 * WHY THIS EXISTS. The Level 1 map is generated by `tools/validate-items.mjs`,
 * so it cannot disagree with the graph it documents. The Level 2 map was
 * written by hand, and within one audit it was already stale: four alignment
 * rows had changed depth or wording in the graph and the document still
 * carried the old ones. A standards document that drifts from the machine-
 * readable source is worse than no document, because it is the copy a
 * department head reads.
 *
 * So the document is derived, and this tool derives it.
 *
 *   node tools/build-l2-map.mjs            # rewrite the document
 *   node tools/build-l2-map.mjs --check    # non-zero if it is out of date
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { alignmentOf, practicesOf, alignmentNote, FRAMEWORKS } from '../src/content/standards.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const GRAPH = path.join(ROOT, 'content/graph/algebra1-l2.json');
const OUT = path.join(ROOT, 'content/standards/algebra1-l2-standards-map.md');
const CHECK = process.argv.includes('--check');

const graph = JSON.parse(await readFile(GRAPH, 'utf8'));
const out = [];
const p = (s = '') => out.push(s);

p(`# Standards alignment — ${graph.title}`);
p();
p('Generated from `content/graph/algebra1-l2.json`, which is the source of truth, by');
p('`node tools/build-l2-map.mjs`. Do not edit this file: edit the graph and rebuild.');
p('Every claim below is made by a node and is read through `src/content/standards.js`.');
p();
p('**How to read a depth.** `core` means the mastery gate for that node really tests the');
p('expectation: three unassisted items at band 4 or above, at least one of them outside');
p('notation, in a form or a situation the learner has not practised. `supporting` and');
p('`introduced` mean part of the expectation is met and the row says which part is not.');
p();

const v = graph.verification;
if (v) {
  p('## Verification');
  p();
  p(`Citations last checked **${v.checkedOn}**, against:`);
  p();
  for (const s of v.sources) p(`- ${s}`);
  p();
  p(v.note);
  p();
  for (const c of v.caveats || []) p(`- ${c}`);
  p();
}

p('## Coverage');
p();
p('| Framework | Distinct codes | Claimed `core` |');
p('|---|---|---|');
for (const fw of Object.keys(FRAMEWORKS)) {
  const rows = graph.nodes.flatMap((n) => alignmentOf(n)).filter((a) => a.framework === fw);
  const codes = new Set(rows.map((a) => a.code));
  const core = new Set(rows.filter((a) => a.depth === 'core').map((a) => a.code));
  if (!codes.size) continue;
  p(`| ${FRAMEWORKS[fw].label} | ${codes.size} | ${core.size} |`);
}
p();
p('Process standards are cited under `practices` and are **not** counted as content');
p('coverage. A process standard is how a learner works, not what the unit teaches.');
p();

for (const n of graph.nodes) {
  p(`## \`${n.id}\``);
  p();
  p(`> ${n.bigIdea}`);
  p();
  p(`**Prerequisites.** ${n.prereqs.length ? n.prereqs.map((x) => `\`${x}\``).join(', ') : '— (this unit opens here)'}`);
  p();
  p('| Framework | Code | 19 TAC | Depth | Expectation |');
  p('|---|---|---|---|---|');
  const al = alignmentOf(n);
  for (const a of al) {
    p(`| ${a.framework} | \`${a.code}\` | ${a.citation ? `\`${a.citation}\`` : '—'} | ${a.depth} | ${a.text} |`);
  }
  p();
  const caveats = al.filter((a) => a.caveat);
  if (caveats.length) {
    for (const a of caveats) p(`- **${a.code} — what is NOT claimed.** ${a.caveat}`);
    p();
  }
  p('**What the gate proves.**');
  p();
  for (const fw of Object.keys(FRAMEWORKS)) {
    const note = alignmentNote(n, fw);
    if (note) p(`- *${fw}* — ${note}`);
  }
  p();
  const pr = practicesOf(n);
  const parts = Object.entries(pr).filter(([, l]) => l.length).map(([fw, l]) => `${fw} ${l.join(', ')}`);
  p(`**Process standards.** ${parts.join(' · ')}`);
  p();
  p(`**Misconceptions this node declares.** ${(n.misconceptions || []).map((m) => `\`${m.id}\``).join(', ')}`);
  p();
}

const body = out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
if (CHECK) {
  const now = await readFile(OUT, 'utf8').catch(() => '');
  if (now !== body) {
    console.error('content/standards/algebra1-l2-standards-map.md is out of date — run node tools/build-l2-map.mjs');
    process.exit(1);
  }
  console.log('L2 standards map is in step with the graph.');
} else {
  await writeFile(OUT, body);
  console.log(`wrote ${path.relative(ROOT, OUT)} — ${graph.nodes.length} nodes`);
}
