#!/usr/bin/env node
/**
 * THE PER-WAVE LEDGER — a red gate that runs once a wave may not be forgotten
 * for three of them.
 *
 *   node tools/gate-ledger.mjs                 # what the ledger holds, and how stale it is
 *   node tools/gate-ledger.mjs --self-test     # the fingerprint and the staleness rule, planted against
 *
 * WHY THIS FILE EXISTS
 *
 * `tools/check-all.mjs` had two lists: gates the build runs, and gates left out
 * with a written reason. That accounting closed one hole — an omission nobody
 * chose — and left the one behind it wide open. A gate can be honestly left out
 * of every commit because it costs nine or eighteen minutes of real play, and
 * then never run at all, and NOTHING ANYWHERE SAYS SO. `check:compose` and
 * `check:motion` were both in that state and both RED ON THE SHIPPED ROUTE, and
 * a blind critic re-found their two defects by hand, twice, while `npm run
 * check` printed green.
 *
 * "Run per wave, not per commit" is a real decision. It is only a decision if
 * somebody can tell whether the wave happened. So:
 *
 *   · the LAST RESULT of every per-wave gate is written down here — exit code,
 *     when, and the fingerprint of the tree it was measured on;
 *   · STALENESS IS COMPUTED, not remembered: if the product has changed since
 *     that run, the recorded green is a green about a tree that no longer
 *     exists and `npm run check` says so on every build;
 *   · A RECORDED RED IS STILL RED. It does not decay into "stale" and it is not
 *     softened by the tree having moved. The whole point of writing it down is
 *     that a red gate cannot be quietly aged out.
 *
 * WHAT THE FINGERPRINT COVERS, and why it is content and not mtime.
 *
 * Two things can change a per-wave gate's answer: THE PRODUCT (src/, content/,
 * index.html, vite.config.js — what the game is) and THE GATE ITSELF (the tool
 * files its npm script names, and the command line that names them). Both are
 * hashed by CONTENT. An mtime fingerprint calls a tree changed when somebody
 * opens a file, which trains everybody to ignore the word "stale", and a gate
 * whose staleness marker is noise is the same as a gate with none.
 */
import { createHash } from 'node:crypto';
import { readFile, readdir, stat, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const LEDGER_PATH = path.join(ROOT, 'progress/gate-runs.json');

/** What the game IS. A change to any of it can change what a walk through it finds. */
export const PRODUCT = ['src', 'content', 'index.html', 'vite.config.js'];

/* Files that are output, not source: never fingerprinted, or every capture a
   gate writes would invalidate the gate that wrote it. */
const SKIP_DIR = new Set(['node_modules', '.git', 'dist', 'dist-w16', 'shots', 'scratch', 'docs']);
/*
 * AND THE OTHER OUTPUT, WHICH WAS FINGERPRINTED AND MADE THIS LEDGER
 * IMPOSSIBLE TO SATISFY.
 *
 * `content/STANDARDS.md` is generated by `tools/build-standards.mjs`, and its
 * section 7.4 is READ OUT OF `progress/gate-runs.json` — this file's own
 * output. `npm run check:standards` then byte-compares the document. So the
 * two rules the build enforces were, together, unsatisfiable:
 *
 *   · run `npm run wave` and the ledger moves, so `content/STANDARDS.md` is
 *     out of step and `check:standards` is RED;
 *   · regenerate the document to fix that, and `content/` changes, so
 *     `hashPaths(PRODUCT)` changes, so `classify()` calls every gate that had
 *     just passed STALE — and a stale route-scope gate fails the build exactly
 *     as a red one does.
 *
 * Exactly one of the two was always red, whichever order anybody worked in,
 * and the state the ledger exists to produce — a route gate recorded FRESH —
 * was the one state the document could never print, because writing "passed,
 * on this tree" was itself the edit that made it untrue. Measured on this
 * tree: one appended byte in `content/STANDARDS.md` moves the product hash
 * from f10a5f5c… to b9365b09….
 *
 * Markdown under `content/` is generated prose for a human reader. Nothing in
 * `src/` imports a `.md`, no `check:` script names one (`toolsNamedBy` does
 * not even match the extension), and no per-wave gate's reading can change
 * because a sentence in a report did. So it is output, like `shots/`, and it
 * is excluded on the same grounds. Everything a gate could actually read —
 * `content/*.json`, `content/graph/*`, `content/lang/*.js` — still moves the
 * fingerprint, and the self-test below plants both directions.
 */
const SKIP_EXT = new Set(['.md']);

async function walk(abs, rel, out) {
  let st;
  try { st = await stat(abs); } catch { return; }
  if (st.isFile()) { if (!SKIP_EXT.has(path.extname(abs))) out.push([rel, abs]); return; }
  if (!st.isDirectory()) return;
  const base = path.basename(abs);
  if (SKIP_DIR.has(base)) return;
  for (const name of (await readdir(abs)).sort()) {
    if (name.startsWith('.')) continue;
    await walk(path.join(abs, name), `${rel}/${name}`, out);
  }
}

/**
 * A content hash over a list of files and directories.
 *
 * Every file contributes its path AND its own digest, so a rename is a change
 * and two files swapping contents is a change. Missing paths contribute the
 * word "missing" rather than being skipped — a deleted source file has to move
 * the fingerprint too.
 *
 * @param {string[]} paths repo-relative
 * @returns {Promise<string>} 40 hex characters
 */
export async function hashPaths(paths, root = ROOT) {
  const files = [];
  for (const p of [...paths].sort()) await walk(path.join(root, p), p, files);
  const h = createHash('sha1');
  if (!files.length) h.update('EMPTY\0');
  for (const [rel, abs] of files.sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
    let body;
    try { body = await readFile(abs); } catch { body = Buffer.from('missing'); }
    h.update(rel);
    h.update('\0');
    h.update(createHash('sha1').update(body).digest());
    h.update('\n');
  }
  return h.digest('hex');
}

/**
 * The tool files an npm script really runs.
 *
 * A gate's command is `node tools/critic/motion.mjs --self-test && tools/critic/rungate.sh …`,
 * so the files that decide its verdict are named in the command itself. Pulling
 * them out of the string means adding a stage to a gate's command line
 * automatically widens what counts as "the gate changed".
 *
 * @param {string} cmd the package.json script body
 * @returns {string[]} repo-relative tool paths, deduplicated, in order
 */
export function toolsNamedBy(cmd) {
  const out = [];
  for (const m of String(cmd || '').matchAll(/(?:^|[\s"'])((?:tools|src|content)\/[\w./-]+\.(?:mjs|js|sh|json))/g)) {
    if (!out.includes(m[1])) out.push(m[1]);
  }
  return out;
}

/**
 * The fingerprint a recorded run is judged against.
 *
 * @param {string} gate      the npm script name
 * @param {Record<string,string>} scripts package.json's scripts block
 * @returns {Promise<{product:string, tool:string, key:string, tools:string[]}>}
 */
export async function fingerprint(gate, scripts, root = ROOT) {
  const cmd = scripts[gate] || '';
  const tools = toolsNamedBy(cmd);
  const product = await hashPaths(PRODUCT, root);
  const tool = createHash('sha1')
    .update(cmd).update('\0')
    .update(await hashPaths(tools, root))
    .digest('hex');
  return { product, tool, key: createHash('sha1').update(product).update(tool).digest('hex'), tools };
}

/** Every per-wave fingerprint in one pass — the product half is hashed once. */
export async function fingerprintAll(gates, scripts, root = ROOT) {
  const product = await hashPaths(PRODUCT, root);
  const out = {};
  for (const gate of gates) {
    const cmd = scripts[gate] || '';
    const tools = toolsNamedBy(cmd);
    const tool = createHash('sha1').update(cmd).update('\0').update(await hashPaths(tools, root)).digest('hex');
    out[gate] = { product, tool, key: createHash('sha1').update(product).update(tool).digest('hex'), tools };
  }
  return out;
}

/** @returns {Promise<Record<string, object>>} gate -> the last recorded run */
export async function readLedger(file = LEDGER_PATH) {
  try {
    const raw = JSON.parse(await readFile(file, 'utf8'));
    return raw && typeof raw === 'object' && raw.runs ? raw.runs : {};
  } catch { return {}; }
}

/** Write one gate's result. Nothing else in the ledger is touched. */
export async function writeRun(gate, row, file = LEDGER_PATH) {
  const runs = await readLedger(file);
  runs[gate] = { gate, ...row };
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, `${JSON.stringify({
    $comment: 'The last recorded result of every per-wave gate. Written by `npm run wave`, read by `npm run check`. '
      + 'A recorded red stays red: staleness never softens it. See tools/gate-ledger.mjs.',
    runs,
  }, null, 1)}\n`);
  return runs[gate];
}

/**
 * THE STALENESS RULE, as a pure function so it can be planted against.
 *
 *   never   nobody has ever run this gate; there is no evidence either way
 *   red     the last run refused something. This outranks staleness — always.
 *   stale   it passed, on a tree that is not this one
 *   fresh   it passed, on this tree
 *
 * @param {object|null} row the recorded run
 * @param {string} key      the fingerprint of the tree now
 */
export function classify(row, key) {
  if (!row || typeof row.code !== 'number') return 'never';
  if (row.code !== 0) return 'red';
  return row.fingerprint && row.fingerprint.key === key ? 'fresh' : 'stale';
}

/** "3 days ago", for a reader. */
export function ago(iso, now = Date.now()) {
  const t = Date.parse(iso || '');
  if (!Number.isFinite(t)) return 'never';
  const s = Math.max(0, (now - t) / 1000);
  if (s < 90) return `${Math.round(s)}s ago`;
  if (s < 5400) return `${Math.round(s / 60)} min ago`;
  if (s < 172800) return `${Math.round(s / 3600)} h ago`;
  return `${Math.round(s / 86400)} days ago`;
}

// ---------------------------------------------------------------------------
// --self-test: the fingerprint, the tool scraper, and the staleness rule, all
// planted against. No gate runs here; this is a second.
// ---------------------------------------------------------------------------
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url) && process.argv.includes('--self-test')) {
  const { mkdtemp, rm } = await import('node:fs/promises');
  const os = await import('node:os');
  let bad = 0;
  const flag = (m) => { console.error(` FAIL ${m}`); bad++; };
  const ok = (m) => console.log(`  ok   ${m}`);
  console.log('gate ledger self-test — the fingerprint and the staleness rule, on planted trees\n');

  const tmp = await mkdtemp(path.join(os.tmpdir(), 'ledger-'));
  await mkdir(path.join(tmp, 'src/world'), { recursive: true });
  await writeFile(path.join(tmp, 'src/world/a.js'), 'export const a = 1;\n');
  await writeFile(path.join(tmp, 'index.html'), '<main></main>\n');

  const h1 = await hashPaths(['src', 'index.html'], tmp);
  const h2 = await hashPaths(['src', 'index.html'], tmp);
  if (h1 !== h2) flag('the same tree hashed twice gave two answers — a fingerprint that drifts makes every gate stale');
  else ok('the same tree hashes the same twice, so "stale" never fires on a tree nobody touched');

  await writeFile(path.join(tmp, 'src/world/a.js'), 'export const a = 2;\n');
  const h3 = await hashPaths(['src', 'index.html'], tmp);
  if (h3 === h1) flag('one changed byte in src/ did not move the fingerprint — a recorded run would look fresh forever');
  else ok('one changed byte in src/ moves the fingerprint');

  await writeFile(path.join(tmp, 'src/world/b.js'), 'export const b = 3;\n');
  if ((await hashPaths(['src', 'index.html'], tmp)) === h3) flag('a NEW file in src/ did not move the fingerprint');
  else ok('a new file moves it too, so added source is not invisible');

  /* THE GENERATED DOCUMENT, PLANTED IN BOTH DIRECTIONS. `content/STANDARDS.md`
     is written FROM progress/gate-runs.json, so if it counted here the ledger
     could never record a fresh route gate: see the note above SKIP_EXT. What
     must still count is everything a gate can actually read. */
  await mkdir(path.join(tmp, 'content/graph'), { recursive: true });
  await writeFile(path.join(tmp, 'content/STANDARDS.md'), '# one\n');
  await writeFile(path.join(tmp, 'content/graph/g.json'), '{"nodes":[]}\n');
  const c1 = await hashPaths(['content'], tmp);
  await writeFile(path.join(tmp, 'content/STANDARDS.md'), '# one\n\nand a regenerated section 7.4\n');
  if ((await hashPaths(['content'], tmp)) !== c1) {
    flag('regenerating a document under content/ moved the fingerprint — every gate that had just passed goes stale, and check:standards and the freshness rule can never both be green');
  } else ok('regenerating a generated document under content/ does NOT move the fingerprint — the document is written from the ledger, so it may not invalidate it');
  await writeFile(path.join(tmp, 'content/graph/g.json'), '{"nodes":[{"id":"a"}]}\n');
  if ((await hashPaths(['content'], tmp)) === c1) {
    flag('one changed byte in content/graph/g.json did not move the fingerprint — a content change would look fresh forever');
  } else ok('…and one changed byte in a graph the game loads still moves it, so the exclusion is markdown and nothing else');

  // the scraper
  const cmd = 'node tools/critic/motion.mjs --self-test && tools/critic/rungate.sh tools/critic/motion.mjs --out shots/motion --minutes 18';
  const named = toolsNamedBy(cmd);
  if (!named.includes('tools/critic/motion.mjs') || !named.includes('tools/critic/rungate.sh')) {
    flag(`the command scraper missed a stage: ${JSON.stringify(named)}`);
  } else ok(`every tool a two-stage command names is fingerprinted (${named.join(', ')})`);
  if (named.length !== 2) flag(`the scraper duplicated a tool: ${JSON.stringify(named)}`);
  else ok('a tool named twice in one command is fingerprinted once');
  if (toolsNamedBy('node tools/gone.mjs').length !== 1) flag('the scraper drops a tool that does not exist on disk — a deleted gate would look unchanged');
  else ok('a tool the command names but disk does not have is still fingerprinted (as missing)');

  // the staleness rule
  const cases = [
    [null, 'K', 'never', 'a gate nobody has ever run'],
    [{ code: 0, fingerprint: { key: 'K' } }, 'K', 'fresh', 'a green run on this exact tree'],
    [{ code: 0, fingerprint: { key: 'OLD' } }, 'K', 'stale', 'a green run on a tree that has since moved'],
    [{ code: 1, fingerprint: { key: 'K' } }, 'K', 'red', 'a red run on this tree'],
    [{ code: 1, fingerprint: { key: 'OLD' } }, 'K', 'red', 'A RED RUN ON AN OLD TREE — red outranks stale, so it cannot be aged out'],
    [{ code: 0 }, 'K', 'stale', 'a run recorded with no fingerprint at all is not credited as fresh'],
    [{}, 'K', 'never', 'a row with no exit code is no evidence'],
  ];
  for (const [row, key, want, why] of cases) {
    const got = classify(row, key);
    if (got !== want) flag(`${why} was classified "${got}", not "${want}"`);
    else ok(`${why} -> ${want}`);
  }

  // round trip: a red result survives being written down and read back
  const file = path.join(tmp, 'ledger.json');
  await writeRun('check:motion', { code: 1, secs: 1080, at: new Date().toISOString(), fingerprint: { key: 'OLD' }, cmd }, file);
  await writeRun('check:compose', { code: 0, secs: 540, at: new Date().toISOString(), fingerprint: { key: 'K' }, cmd }, file);
  const back = await readLedger(file);
  if (back['check:motion']?.code !== 1) flag('a recorded red did not survive the round trip');
  else ok('a recorded red survives the round trip, unchanged');
  if (back['check:compose']?.code !== 0) flag('writing one gate clobbered another');
  else ok('writing one gate leaves every other recorded result alone');
  if (classify(back['check:motion'], 'K') !== 'red') flag('a recorded red went quiet once the tree moved under it');
  else ok('a recorded red is still red three waves later — the defect this ledger exists for');
  if ((await readLedger(path.join(tmp, 'nope.json'))) && Object.keys(await readLedger(path.join(tmp, 'nope.json'))).length) {
    flag('a missing ledger produced rows out of nowhere');
  } else ok('a missing ledger reads as "nobody has run anything", not as green');

  await rm(tmp, { recursive: true, force: true });
  console.log('');
  if (bad) { console.error(`self-test: ${bad} failure(s)\n`); process.exit(1); }
  console.log('self-test: ok — the fingerprint moves only when the product or the gate does, and a recorded red never ages out\n');
  process.exit(0);
}
